services:
  app:
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - LOCAL_PORT=${LOCAL_PORT:-80}
      - LOCAL_PORT_SSL=${LOCAL_PORT_SSL:-443}
    restart: unless-stopped
    container_name: react-starter
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${LOCAL_PORT:-80}:80"
      - "${LOCAL_PORT_SSL:-443}:443"
    volumes:
      - .:/app
      - /app/node_modules
